import { ServiceOrderFormData } from "./types";

export const initialFormData: ServiceOrderFormData = {
  orderNumber: '',
  visitDate: '',
  visitTime: '',
  technicians: [],
  school: '',
  visitLocation: '',
  schoolOpen: '',
  reasonClosed: '',
  visitResponsible: '',
  visitResponsibleRole: '',
  visitObjective: '',
  sieducaDetails: [],
  sieducaEquipmentDetails: '',
  secretaryDetails: [],
  secretaryEquipmentDetails: '',
  otherLocationsDetails: [],
  otherLocationsEquipmentDetails: '',
  internetDetails: [],
  rackDetails: [],
  rackEquipmentDetails: '',
  printerDetails: [],
  printerEquipmentDetails: '',
  visitDescription: '',
  repairDescription: '',
  problemSolved: '',
  reasonNotSolved: '',
  nextTechnicianInstructions: '',
  beforePhotos: [],
  afterPhotos: [],
  completionDate: '',
  completionTime: '',
  completionResponsible: '',
  signedPhoto: [],
};