const initialFormData = {
  unidadeEscolar: "",
  tecnicoResponsavel: "",
  numeroOs: "",
  data: "",
  hora: "",
  notebooksOutroLocal: "",
  tabletsOutroLocal: "",
  solicitacaoDaVisita: "",
  relatorio: "",
  pcsSieduca: "",
  notebooksSieduca: "",
  tabletsSieduca: "",
  estabilizadoresSieduca: "",
  naoHaSieduca: "",
  dellSecretaria: "",
  locadosSecretaria: "",
  outrosSecretaria: "",
  notebooksSecretaria: "",
  tabletsSecretaria: "",
  estabilizadoresSecretaria: "",
  dellOutroLocal: "",
  locadosOutroLocal: "",
  outrosOutroLocal: "",
  estabilizadoresOutroLocal: "",
  naoHaOutroLocal: "",
  redeBr: "",
  internetNasEscolas: "",
  educacaoConectada: "",
  naoHaProvedor: "",
  rack: "",
  switch: "",
  roteador: "",
  oki: "",
  kyocera: "",
  hp: "",
  ricoh: "",
  outrasImpressoras: "",
  sim: "",
  nao: "",
  solucionado: "" // Adicionar a propriedade solucionado
};

export default initialFormData;