-- CreateTable
CREATE TABLE "OSExterna" (
    "id" SERIAL NOT NULL,
    "unidadeEscolar" TEXT,
    "tecnicoResponsavel" TEXT,
    "emailResponsavel" TEXT,
    "fotosAntes" JSONB,
    "fotosDepois" JSONB,
    "pcsProprio" INTEGER,
    "pcsLocado" INTEGER,
    "notebooksProprio" INTEGER,
    "notebooksLocado" INTEGER,
    "monitoresProprio" INTEGER,
    "monitoresLocado" INTEGER,
    "estabilizadoresProprio" INTEGER,
    "estabilizadoresLocado" INTEGER,
    "tabletsProprio" INTEGER,
    "tabletsLocado" INTEGER,
    "pcsProprioOutrosLocais" INTEGER,
    "pcsLocadoOutrosLocais" INTEGER,
    "notebooksProprioOutrosLocais" INTEGER,
    "notebooksLocadoOutrosLocais" INTEGER,
    "monitoresProprioOutrosLocais" INTEGER,
    "monitoresLocadoOutrosLocais" INTEGER,
    "estabilizadoresProprioOutrosLocais" INTEGER,
    "estabilizadoresLocadoOutrosLocais" INTEGER,
    "tabletsProprioOutrosLocais" INTEGER,
    "tabletsLocadoOutrosLocais" INTEGER,
    "pecasOuMaterial" TEXT,
    "relatorio" TEXT,
    "solicitacaoDaVisita" TEXT,
    "temLaboratorio" BOOLEAN,
    "redeBr" TEXT,
    "educacaoConectada" TEXT,
    "naoHaProvedor" TEXT,
    "rack" INTEGER,
    "switch" INTEGER,
    "roteador" INTEGER,
    "oki" INTEGER,
    "kyocera" INTEGER,
    "hp" INTEGER,
    "ricoh" INTEGER,
    "outrasImpressoras" TEXT,
    "solucionado" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OSExterna_pkey" PRIMARY KEY ("id")
);
